# Generated by Django 5.1.2 on 2025-04-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("divert", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geopoint",
            name="owner",
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name="geopoint",
            name="pod",
            field=models.CharField(max_length=12),
        ),
    ]
