services:
  taft:
    image: taft
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 hydro\manage.py runserver 0.0.0.0:8000 --nothreading --noreload"]
    ports:
      - 5432:5432
      - 8000:8000
      - 5678:5678
